% Coded by:     Peter Sutor Jr.
% Last edit:    3/6/2016
% -------------------------------------------------------------------------
% DESCRIPTION -------------------------------------------------------------
%
% Tests the Basis Pursuit problem solver using ADMM. Basis Pursuit 
% minimizes for x the objective function:
%    obj(x) = ||x||_1, 
%    subject to D*x = s,
% where D is a matrix and s is a column vector of appropriate length. Thus,
% x is a column vector of the same length. If D is an m by n matrix, we
% require m < n, i.e., an underdetermined system. See function basispursuit
% for more details about how to solve this problem with ADMM.
% 
% The test creates random data for D and s, of size rows by cols, given as 
% inputs. The seed specifies the seed value to use in random number 
% generation, for repeatability. The value errtol is the relative error 
% tolerance from the 'true' solution that is allowed for the test to be
% successful. The variable quiet determines whether to suppress output and
% graphs.
%
% Consult the user manual for instructions and examples on how to set the
% options argument to customize the solver.
%
% NOTE: If basispursuittest is executed with no arguments, it will create a
% demo test of random data of size m = 2^6, n = 2^7. The random values are
% generated by the function rng with the 'shuffle' option to be seedless. 
% The rows and cols are set to m and n, with an errtol of 0.001, and 
% quiet = 0. The options struct is set to empty, thus using ADMM's default
% setup.

function [results, test] = ...
    basispursuittest(seed, rows, cols, errtol, quiet, options)
% INPUTS ------------------------------------------------------------------
% seed:     The seed used to generate random data in the test.
% rows:     The variable m in the m by n problem specified in the problem
%           being tested, described in the description above.
% cols:     The variable n in the m by n problem specified in the problem
%           being tested, described in the description above.
% errtol:   The relative error from the 'true' solution that is allowed for
%           the test to be considered successfully convergent. Typical
%           values are 0.01 or 0.001, corresponding to 1% or 0.1% accuracy
%           to the true solution.
% quiet:    A binary value specifying whether to show output and graphs for
%           the test.
% options:  A struct containing options customizing the ADMM execution. If
%           no options are provided (an empty or irrelevant struct is given
%           as the options parameter), default settings are applied, as 
%           mentioned in the user manual.
% 
% OUTPUTS -----------------------------------------------------------------
% results:  A struct containing the results of the execution, including the
%           optimized values for x, z and u that optimize the objective for
%           x, runtime evaluations, records of each iteration, etc. Consult
%           the user manual for more details on the results struct, or
%           simply check what the variable contains in the Matlab 
%           interpreter after execution.
% test:     A struct containing the details of the random test that was
%           performed, including the random data generated, how correct it
%           was, whether it reached the correct tolerance (successful test)
%           and so on. Consult the user manual for more details on the test
%           struct, or simply check what the variable contains in the 
%           Matlab interpreter after execution.
% -------------------------------------------------------------------------


% Persistent global variable to indicate whether paths have been set or
% not.
global setup;

% Check if paths need to be set up.
if isempty(setup)
    currpath = pwd;                         % Save current directory.
    
    % Get directory of this function (assumed to be in testers folder of 
    % ADMM library).
    filepath = mfilename('fullpath');       % Get current file path.
    filepath = filepath(1:length(filepath) - length(mfilename()));
    
    % Switch to directory containing setuppaths and run it. Then switch
    % back to original directory. Save setup = 1 to indicate to all other
    % functions that setup has already been done.
    cd(filepath);
    cd('..');
    setuppaths(1);
    cd(currpath);
    setup = 1;
end

% Check if no arguments were given. If so, run the default test, otherwise
% proceed with user's inputs.
if nargin == 0
    % Demo test's default settings.
    rng('shuffle');
    rows = 2^6;
    cols = 2^7;
    errtol = 0.001;
    quiet = 0;
    options = struct();
else
    % Error checking on input.
    [seed, rows, cols, errtol, quiet] = ...
        errorcheck(seed, rows, cols, errtol, quiet, options);

    rng('default');                     % Default RNG.
    rng(seed);                          % Seed the RNG.
end

% Generate a Basis Pursuit problem where we already know the solution.
% Namely, make D a normally distributed random matrix, and choose a
% particular solution x. Evaluate the objective function on this x and make
% the vector s the product of D and this x. This guarantees x to be the
% minimized solution, and we expect ADMM to return the same x.
D = randn(rows, cols);                  % The normally random matrix D.
testx = sprandn(cols, 1, 0.1*cols);     % The true, optimal x we choose.
testobj = norm(testx, 1);               % Evaluate the objective on this x.
s = D*testx;                            % Compute s as D*x, since we want 
                                        % the condition D*x = s.

% Set the options struct for ADMM.
options.objevals = 1;                   % We want objective evaluations.
options.maxiters = 10000;               % Up to 10,000 iterations.
options.convtest = 0;                   % Want convergence testing.
options.solver = 'basispursuit';        % Testing Basis Pursuit solver.

% Use the Basis Pursuit solver to get our solution.
results = basispursuit(D, s, options);

% Store some results from the ADMM execution.
xopt = results.xopt;                    % ADMM's optimal solution x.
admmopt = results.objopt;               % ADMM's optimal objective value.
objopt = norm(xopt, 1);                 % The true objective eval.

% Compute the average relative error from true solution (D*xopt - s should 
% be close to 0), relative to s.
relerror = (sum(abs((D*xopt - s)./(D*xopt)))/length(s));

% Check to see if the test failed or not (was within error tolerance).
if (testobj >= objopt && relerror <= errtol)
    failed = 0;
else
    failed = 1;
end

% Populate the fields of the returned test struct, containing the details
% of the test that we performed. 
test.D = D;
test.s = s;
test.testx = testx;
test.testobj = testobj;
test.xopt = xopt;
test.admmopt = admmopt;
test.objopt = objopt;
test.failed = failed;
test.relerror = relerror;
test.constraintresidual = norm(D*xopt - s, 'fro');  % Constraint residual.
test.steps = results.steps;                         % Number of iterations.
test.errtol = errtol;
test.solver = 'basispursuit';

% Show graphs and output if allowed by user.
if ~quiet
    showresults(results, test, options);
end

end
% -------------------------------------------------------------------------



% -------------------------------------------------------------------------
% DESCRIPTION -------------------------------------------------------------
% 
% Simply checks for any user error on same input, stops if error is
% detected. If input is correct, return info needed for problem.

function [seed, rows, cols, errtol, quiet] = ...
    errorcheck(seed, rows, cols, errtol, quiet, options)
% INPUTS ------------------------------------------------------------------
% Same as for the basispursuittest function.
% 
% OUTPUTS -----------------------------------------------------------------
% Same as the inputs, just potentially altered values for strange input.
% -------------------------------------------------------------------------


% Check for invalid input and report errors / terminate if detected.
if (~isnumeric(seed) || floor(seed) < 0)
    error('Given RNG seed is not a nonnegative integer!');
elseif (~isnumeric(rows) || floor(real(rows)) < 0)
    error('Given number of rows is not a nonnegative integer!');
elseif (~isnumeric(cols) || floor(real(cols)) < 0)
    error('Given number of columns is not a nonnegative integer!');
elseif (~isnumeric(errtol) || real(errtol) <= 0)
    error('Given error tolerance errtol is not a positive number!');
else
    seed = floor(real(seed));   % Set the seed to valid value.
    rows = floor(real(rows));   % Set the rows to valid value.
    cols = floor(real(cols));   % Set the columnss to valid value.
    errtol = real(errtol);      % Set error tolerance to valid value.
end

% Check if the number of rows exceeds that of the columns. If it does,
% report that the system is overdetermined and should be solved through
% more efficient means. If the problem is square, then there is no need to
% perform Basis Pursuit and we can solve the problem by simply solving 
% D*x = s (there is only one x that will satisfy this, and thus is the
% minumum value for ||x||_1).
if rows > cols
    error(['Overdetermined system Dx = s, as D has more rows than', ...
        'columns; use Unwrapped ADMM solver for efficiency, instead.']);
elseif rows == cols
    error(['Square matrix problem Dx = s; ', ...
        'don''t need Basis Pursuit to solve this!']);
end

% Only set output to be suppressed if specified.
if (~isnumeric(quiet) || floor(real(quiet)) ~= 1)
    quiet = 0;
else
    quiet = 1;
end

% Check that the given options is actually a struct...
if ~isstruct(options)
    error('Given options is not a struct! At least pass empty struct!');
end

end